# Generated by Django 2.0.3 on 2018-03-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_top',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
